### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Gideon877** [MichaelCDavids/matching-days#1]
Hi Mike, 

I have checked your matching day exercise and everything is working fine. 
I'm impressed.
@MichaelCDavids 
 @avermeulen

**Comment by MichaelCDavids** [comment]
Thanks Thabang,

We no longer using just JavaScript. Going with Handlebars Templating.
Check it out and let me know what you think about it.
I managed to fix that issue last night.

@Gideon877
