### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by Gideon877** [MichaelCDavids/matching-days#2]
Hi @MichaelCDavids 

I think you should work on naming variables better as it might be confusing sometimes. for eg, getOneDay will be better if is getDayOne or getFirstDay.

https://github.com/MichaelCDavids/matching-days/blob/0d8d570d604fa8cde3afec03158104107484cc84/js/matching-days-factory.js#L71-L74

**Comment by MichaelCDavids** [comment]
I actually deleted those didn't need them
